repos:
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: v3.5.0
    hooks:
      - id: gdformat
        name: Format GDScript files
        entry: gdformat
        language: python
        types: [text]
        files: \.gd$
        args: []
